# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

fit_mlr <- function(y, x) {
    .Call('_LinearReg_fit_mlr', PACKAGE = 'LinearReg', y, x)
}

fit_mlr_null <- function(y, x) {
    .Call('_LinearReg_fit_mlr_null', PACKAGE = 'LinearReg', y, x)
}

fit_slr <- function(y, x) {
    .Call('_LinearReg_fit_slr', PACKAGE = 'LinearReg', y, x)
}

